# Adjust Layout
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

st.set_page_config(layout="wide", page_title="Ecommerce KPI Dashboard", page_icon=":shopping_cart:")

# Custom CSS for PowerBI/Tableau-like look
st.markdown("""
    <style>
    .metric-card {
        background: #f8f9fa;
        padding: 20px;
        border-radius: 6px;
        border-left: 4px solid #1f77b4;
        text-align: center;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
    }
    .metric-value {
        font-size: 28px;
        font-weight: 600;
        margin: 10px 0;
        color: #000;
    }
    .metric-label {
        font-size: 13px;
        color: #666;
        font-weight: 500;
    }
    .section-title {
        color: #1f77b4;
        font-size: 18px;
        font-weight: 600;
        margin-top: 25px;
        margin-bottom: 15px;
        border-bottom: 2px solid #e0e0e0;
        padding-bottom: 8px;
    }
    </style>
""", unsafe_allow_html=True)

# Make centered title
st.markdown("<h1 style='text-align: center; color: #1f77b4; font-size: 32px;'>📊 E-Commerce KPI Dashboard</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; color: #999; font-size: 14px; margin-bottom: 30px;'>Real-time Performance Metrics & Insights</p>", unsafe_allow_html=True)

# Read Data
@st.cache_data
def load_data():
    df = pd.read_csv("cleaned_df.csv")
    df['order_date'] = pd.to_datetime(df['order_date'])
    df['delivery_date'] = pd.to_datetime(df['delivery_date'])
    return df

df = load_data()

# Calculate Key Metrics
total_revenue = df['total_price'].sum()
total_orders = len(df)
avg_order_value = df['total_price'].mean()
total_customers = df['customer_name'].nunique()
avg_delivery_days = df['delivery_days'].mean()
repeat_customers = df[df.groupby('customer_name')['customer_name'].transform('count') > 1]['customer_name'].nunique()

# Display KPI Metrics
st.markdown("<div class='section-title'>📈 Key Performance Indicators</div>", unsafe_allow_html=True)

col1, col2, col3, col4, col5, col6 = st.columns(6)

with col1:
    st.markdown(f"""
    <div class='metric-card'>
        <div class='metric-label'>Total Revenue</div>
        <div class='metric-value'>${total_revenue:,.0f}</div>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.markdown(f"""
    <div class='metric-card'>
        <div class='metric-label'>Total Orders</div>
        <div class='metric-value'>{total_orders:,}</div>
    </div>
    """, unsafe_allow_html=True)

with col3:
    st.markdown(f"""
    <div class='metric-card'>
        <div class='metric-label'>Avg Order Value</div>
        <div class='metric-value'>${avg_order_value:,.0f}</div>
    </div>
    """, unsafe_allow_html=True)

with col4:
    st.markdown(f"""
    <div class='metric-card'>
        <div class='metric-label'>Total Customers</div>
        <div class='metric-value'>{total_customers:,}</div>
    </div>
    """, unsafe_allow_html=True)

with col5:
    st.markdown(f"""
    <div class='metric-card'>
        <div class='metric-label'>Avg Delivery Days</div>
        <div class='metric-value'>{avg_delivery_days:.1f}</div>
    </div>
    """, unsafe_allow_html=True)

with col6:
    st.markdown(f"""
    <div class='metric-card'>
        <div class='metric-label'>Repeat Customers</div>
        <div class='metric-value'>{repeat_customers:,}</div>
    </div>
    """, unsafe_allow_html=True)

# Revenue Trends
st.markdown("<div class='section-title'>💰 Monthly Revenue Trend</div>", unsafe_allow_html=True)

df['month'] = df['order_date'].dt.strftime('%Y-%m')
monthly_revenue = df.groupby('month')['total_price'].sum().reset_index()
monthly_revenue.columns = ['Month', 'Revenue']

fig_revenue = px.line(monthly_revenue, x='Month', y='Revenue', 
                     title='Revenue Growth Over Time',
                     markers=True, line_shape='spline',
                     labels={'Revenue': 'Total Revenue ($)', 'Month': 'Month'})
fig_revenue.update_traces(line=dict(color='#1f77b4', width=3), marker=dict(size=8))
fig_revenue.update_layout(hovermode='x unified', height=400, template='plotly_white')
st.plotly_chart(fig_revenue, use_container_width=True)

# Product Performance & Customer Insights
col1, col2 = st.columns(2)

with col1:
    st.markdown("<div class='section-title'>🏆 Top 5 Best Selling Products</div>", unsafe_allow_html=True)
    
    top_products = df.groupby('product_name').agg({
        'sales_id': 'count',
        'total_price': 'sum'
    }).reset_index()
    top_products.columns = ['Product', 'Orders', 'Revenue']
    top_products = top_products.sort_values('Revenue', ascending=False).head(5)
    
    fig_products = px.bar(top_products, x='Revenue', y='Product', 
                         orientation='h', 
                         title='Revenue Generated by Top 5 Products',
                         color='Revenue', color_continuous_scale='Blues')
    fig_products.update_layout(height=400, showlegend=False, template='plotly_white')
    st.plotly_chart(fig_products, use_container_width=True)

with col2:
    st.markdown("<div class='section-title'>👥 Top 5 Customers by Spending</div>", unsafe_allow_html=True)
    
    top_customers = df.groupby('customer_name').agg({
        'total_price': 'sum',
        'sales_id': 'count'
    }).reset_index()
    top_customers.columns = ['Customer', 'Total Spent', 'Orders']
    top_customers = top_customers.sort_values('Total Spent', ascending=False).head(5)
    
    fig_customers = px.bar(top_customers, x='Total Spent', y='Customer',
                          orientation='h',
                          title='Top 5 Customers by Total Spending',
                          color='Total Spent', color_continuous_scale='Blues')
    fig_customers.update_layout(height=400, showlegend=False, template='plotly_white')
    st.plotly_chart(fig_customers, use_container_width=True)

# Product Type & Gender Analysis
col1, col2 = st.columns(2)

with col1:
    st.markdown("<div class='section-title'>📦 Sales by Product Type</div>", unsafe_allow_html=True)
    
    product_sales = df.groupby('product_type').agg({
        'sales_id': 'count',
        'total_price': 'sum'
    }).reset_index()
    product_sales.columns = ['Product Type', 'Orders', 'Revenue']
    product_sales = product_sales.sort_values('Revenue', ascending=False)
    
    fig_product_type = px.pie(product_sales, values='Revenue', names='Product Type',
                             title='Revenue Distribution by Product Type',
                             color_discrete_sequence=px.colors.sequential.Blues)
    fig_product_type.update_layout(height=400, template='plotly_white')
    st.plotly_chart(fig_product_type, use_container_width=True)

with col2:
    st.markdown("<div class='section-title'>👨‍👩‍👧‍👦 Sales by Gender</div>", unsafe_allow_html=True)
    
    gender_sales = df.groupby('gender').agg({
        'sales_id': 'count',
        'total_price': 'sum'
    }).reset_index()
    gender_sales.columns = ['Gender', 'Orders', 'Revenue']
    
    fig_gender = px.pie(gender_sales, values='Revenue', names='Gender',
                       title='Revenue Distribution by Gender',
                       color_discrete_map={'Male': '#1f77b4', 'Female': '#aec7e8'})
    fig_gender.update_layout(height=400, template='plotly_white')
    st.plotly_chart(fig_gender, use_container_width=True)

# Geographic & Size Insights
col1, col2 = st.columns(2)

with col1:
    st.markdown("<div class='section-title'>🌍 Top 10 States by Revenue</div>", unsafe_allow_html=True)
    
    state_revenue = df.groupby('state').agg({
        'total_price': 'sum'
    }).reset_index()
    state_revenue.columns = ['State', 'Revenue']
    state_revenue = state_revenue.sort_values('Revenue', ascending=False).head(10)
    
    fig_states = px.bar(state_revenue, x='State', y='Revenue',
                       title='Revenue by Top 10 States',
                       color='Revenue', color_continuous_scale='Blues')
    fig_states.update_layout(height=400, showlegend=False, template='plotly_white')
    st.plotly_chart(fig_states, use_container_width=True)

with col2:
    st.markdown("<div class='section-title'>👕 Popular Sizes</div>", unsafe_allow_html=True)
    
    size_sales = df.groupby('size').agg({
        'sales_id': 'count',
        'total_price': 'sum'
    }).reset_index()
    size_sales.columns = ['Size', 'Orders', 'Revenue']
    size_sales = size_sales.sort_values('Revenue', ascending=False)
    
    fig_sizes = px.bar(size_sales, x='Size', y='Revenue',
                      title='Revenue by Product Size',
                      color='Revenue', color_continuous_scale='Blues')
    fig_sizes.update_layout(height=400, showlegend=False, template='plotly_white')
    st.plotly_chart(fig_sizes, use_container_width=True)

# Customer Demographics
col1, col2 = st.columns(2)

with col1:
    st.markdown("<div class='section-title'>📊 Age Distribution of Customers</div>", unsafe_allow_html=True)
    
    fig_age = px.histogram(df, x='age', nbins=20,
                          title='Customer Age Distribution',
                          color_discrete_sequence=['#1f77b4'])
    fig_age.update_layout(height=400, showlegend=False, template='plotly_white')
    fig_age.update_xaxes(title='Age')
    fig_age.update_yaxes(title='Number of Customers')
    st.plotly_chart(fig_age, use_container_width=True)

with col2:
    st.markdown("<div class='section-title'>📈 Average Order Value by Gender & Age Group</div>", unsafe_allow_html=True)
    
    df['age_group'] = pd.cut(df['age'], bins=[0, 25, 35, 45, 100], 
                            labels=['18-25', '26-35', '36-45', '45+'])
    age_gender_aov = df.groupby(['age_group', 'gender']).agg({
        'total_price': 'mean'
    }).reset_index()
    age_gender_aov.columns = ['Age Group', 'Gender', 'Avg Order Value']
    
    fig_aov = px.bar(age_gender_aov, x='Age Group', y='Avg Order Value', color='Gender',
                    title='Average Order Value by Age Group & Gender',
                    barmode='group',
                    color_discrete_map={'Male': '#1f77b4', 'Female': '#aec7e8'})
    fig_aov.update_layout(height=400, template='plotly_white')
    st.plotly_chart(fig_aov, use_container_width=True)

# Top Colors & Delivery Performance
col1, col2 = st.columns(2)

with col1:
    st.markdown("<div class='section-title'>🎨 Popular Colors</div>", unsafe_allow_html=True)
    
    color_sales = df.groupby('colour').agg({
        'sales_id': 'count'
    }).reset_index()
    color_sales.columns = ['Colour', 'Orders']
    color_sales = color_sales.sort_values('Orders', ascending=False).head(8)
    
    fig_colors = px.bar(color_sales, x='Colour', y='Orders',
                       title='Top 8 Most Popular Colors',
                       color='Orders', color_continuous_scale='Blues')
    fig_colors.update_layout(height=400, showlegend=False, template='plotly_white')
    st.plotly_chart(fig_colors, use_container_width=True)

with col2:
    st.markdown("<div class='section-title'>🚚 Delivery Performance</div>", unsafe_allow_html=True)
    
    delivery_stats = df.groupby('product_type').agg({
        'delivery_days': ['mean', 'min', 'max']
    }).reset_index()
    delivery_stats.columns = ['Product Type', 'Avg Days', 'Min Days', 'Max Days']
    
    fig_delivery = px.bar(delivery_stats, x='Product Type', y='Avg Days',
                         title='Average Delivery Days by Product Type',
                         color='Avg Days', color_continuous_scale='Blues')
    fig_delivery.update_layout(height=400, showlegend=False, template='plotly_white')
    st.plotly_chart(fig_delivery, use_container_width=True)

# Summary Stats Table
st.markdown("<div class='section-title'>📋 Detailed Summary Statistics</div>", unsafe_allow_html=True)

summary_data = {
    'Metric': [
        'Total Revenue',
        'Total Orders',
        'Average Order Value',
        'Total Unique Customers',
        'Repeat Customers',
        'Average Customer Spending',
        'Average Delivery Time',
        'Most Popular Product Type',
        'Most Popular Color',
        'Best Performing State'
    ],
    'Value': [
        f'${total_revenue:,.2f}',
        f'{total_orders:,}',
        f'${avg_order_value:,.2f}',
        f'{total_customers:,}',
        f'{repeat_customers:,}',
        f'${df.groupby("customer_name")["total_price"].sum().mean():,.2f}',
        f'{avg_delivery_days:.1f} days',
        f'{df["product_type"].value_counts().index[0]}',
        f'{df["colour"].value_counts().index[0]}',
        f'{df.groupby("state")["total_price"].sum().idxmax()}'
    ]
}

summary_df = pd.DataFrame(summary_data)
st.dataframe(summary_df, use_container_width=True, hide_index=True)

st.markdown("---")
st.markdown("<p style='text-align: center; color: #666; font-size: 12px;'>Dashboard Updated: " + 
            pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S") + "</p>", unsafe_allow_html=True)